### ISSUE TITLE
Opcodes geändert

### ISSUE THREAD

**Issue by Nilix007** [svenstaro/uni-projekt#1]
Moin,

ich musste die opcodes leicht verändern:
- ALU Ops fangen jetzt immer mit 00 an.
  - Dabei haben sich nur MUL und DIV verändert. MLL ist entfallen.
- MEM Ops sind relativ zum pc, wenn ein immediate übergeben wird.
- jmp und call sind in das neue präfix 11100 verschoben worden.
- swi ist hinzugekommen. (Software Interrupt)
- adr ist hinzugekommen. ('adress of')

Aktualisierte Dokumentation ist unter new_opcodes zu finden.

Wenn sich niemand beschwert, landet das demnächst im Master.

Gruß,

Felix

**Comment by hellow554** [comment]
keine Beschwerde
